# /etc/filebeat/filebeat.yml
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/snort/snort.alert.fast  # Path to Snort alert file
  fields:
    log_type: snort_alert
  fields_under_root: true
  multiline.pattern: '^\d{2}/\d{2}-\d{2}:\d{2}:\d{2}\.\d+'  # Start of a new log entry
  multiline.negate: true
  multiline.match: after

output.logstash:
  hosts: ["localhost:5044"]  # Forward logs to Logstash

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

